// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: container.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_container_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_container_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_container_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_container_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_container_2eproto;
namespace org {
namespace infinity {
namespace idm {
class Container;
struct ContainerDefaultTypeInternal;
extern ContainerDefaultTypeInternal _Container_default_instance_;
}  // namespace idm
}  // namespace infinity
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
template<> ::org::infinity::idm::Container* Arena::CreateMaybeMessage<::org::infinity::idm::Container>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace org {
namespace infinity {
namespace idm {

// ===================================================================

class Container final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:org.infinity.idm.Container) */ {
 public:
  inline Container() : Container(nullptr) {}
  ~Container() override;
  explicit constexpr Container(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Container(const Container& from);
  Container(Container&& from) noexcept
    : Container() {
    *this = ::std::move(from);
  }

  inline Container& operator=(const Container& from) {
    CopyFrom(from);
    return *this;
  }
  inline Container& operator=(Container&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Container& default_instance() {
    return *internal_default_instance();
  }
  static inline const Container* internal_default_instance() {
    return reinterpret_cast<const Container*>(
               &_Container_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Container& a, Container& b) {
    a.Swap(&b);
  }
  inline void Swap(Container* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Container* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Container* New() const final {
    return new Container();
  }

  Container* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Container>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Container& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Container& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Container* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "org.infinity.idm.Container";
  }
  protected:
  explicit Container(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartBeatFieldNumber = 1,
    kStartTickFieldNumber = 2,
    kLengthFieldNumber = 3,
    kPatternFieldNumber = 4,
  };
  // uint32 startBeat = 1;
  void clear_startbeat();
  ::PROTOBUF_NAMESPACE_ID::uint32 startbeat() const;
  void set_startbeat(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_startbeat() const;
  void _internal_set_startbeat(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 startTick = 2;
  void clear_starttick();
  ::PROTOBUF_NAMESPACE_ID::uint32 starttick() const;
  void set_starttick(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_starttick() const;
  void _internal_set_starttick(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint64 length = 3;
  void clear_length();
  ::PROTOBUF_NAMESPACE_ID::uint64 length() const;
  void set_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_length() const;
  void _internal_set_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 pattern = 4;
  void clear_pattern();
  ::PROTOBUF_NAMESPACE_ID::uint32 pattern() const;
  void set_pattern(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_pattern() const;
  void _internal_set_pattern(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:org.infinity.idm.Container)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 startbeat_;
  ::PROTOBUF_NAMESPACE_ID::uint32 starttick_;
  ::PROTOBUF_NAMESPACE_ID::uint64 length_;
  ::PROTOBUF_NAMESPACE_ID::uint32 pattern_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_container_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Container

// uint32 startBeat = 1;
inline void Container::clear_startbeat() {
  startbeat_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Container::_internal_startbeat() const {
  return startbeat_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Container::startbeat() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Container.startBeat)
  return _internal_startbeat();
}
inline void Container::_internal_set_startbeat(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  startbeat_ = value;
}
inline void Container::set_startbeat(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_startbeat(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Container.startBeat)
}

// uint32 startTick = 2;
inline void Container::clear_starttick() {
  starttick_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Container::_internal_starttick() const {
  return starttick_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Container::starttick() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Container.startTick)
  return _internal_starttick();
}
inline void Container::_internal_set_starttick(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  starttick_ = value;
}
inline void Container::set_starttick(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_starttick(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Container.startTick)
}

// uint64 length = 3;
inline void Container::clear_length() {
  length_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Container::_internal_length() const {
  return length_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Container::length() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Container.length)
  return _internal_length();
}
inline void Container::_internal_set_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  length_ = value;
}
inline void Container::set_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Container.length)
}

// uint32 pattern = 4;
inline void Container::clear_pattern() {
  pattern_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Container::_internal_pattern() const {
  return pattern_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Container::pattern() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Container.pattern)
  return _internal_pattern();
}
inline void Container::_internal_set_pattern(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  pattern_ = value;
}
inline void Container::set_pattern(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_pattern(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Container.pattern)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace idm
}  // namespace infinity
}  // namespace org

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_container_2eproto
