// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: effect.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_effect_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_effect_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "tparam.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_effect_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_effect_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_effect_2eproto;
namespace org {
namespace infinity {
namespace idm {
class Effector;
struct EffectorDefaultTypeInternal;
extern EffectorDefaultTypeInternal _Effector_default_instance_;
}  // namespace idm
}  // namespace infinity
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
template<> ::org::infinity::idm::Effector* Arena::CreateMaybeMessage<::org::infinity::idm::Effector>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace org {
namespace infinity {
namespace idm {

// ===================================================================

class Effector final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:org.infinity.idm.Effector) */ {
 public:
  inline Effector() : Effector(nullptr) {}
  ~Effector() override;
  explicit constexpr Effector(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Effector(const Effector& from);
  Effector(Effector&& from) noexcept
    : Effector() {
    *this = ::std::move(from);
  }

  inline Effector& operator=(const Effector& from) {
    CopyFrom(from);
    return *this;
  }
  inline Effector& operator=(Effector&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Effector& default_instance() {
    return *internal_default_instance();
  }
  static inline const Effector* internal_default_instance() {
    return reinterpret_cast<const Effector*>(
               &_Effector_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Effector& a, Effector& b) {
    a.Swap(&b);
  }
  inline void Swap(Effector* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Effector* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Effector* New() const final {
    return new Effector();
  }

  Effector* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Effector>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Effector& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Effector& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Effector* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "org.infinity.idm.Effector";
  }
  protected:
  explicit Effector(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParamsFieldNumber = 4,
    kNameFieldNumber = 1,
    kMixFieldNumber = 3,
    kIsOnFieldNumber = 2,
  };
  // repeated .org.infinity.idm.TrackParam params = 4;
  int params_size() const;
  private:
  int _internal_params_size() const;
  public:
  void clear_params();
  ::org::infinity::idm::TrackParam* mutable_params(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::TrackParam >*
      mutable_params();
  private:
  const ::org::infinity::idm::TrackParam& _internal_params(int index) const;
  ::org::infinity::idm::TrackParam* _internal_add_params();
  public:
  const ::org::infinity::idm::TrackParam& params(int index) const;
  ::org::infinity::idm::TrackParam* add_params();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::TrackParam >&
      params() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // double mix = 3;
  void clear_mix();
  double mix() const;
  void set_mix(double value);
  private:
  double _internal_mix() const;
  void _internal_set_mix(double value);
  public:

  // bool isOn = 2;
  void clear_ison();
  bool ison() const;
  void set_ison(bool value);
  private:
  bool _internal_ison() const;
  void _internal_set_ison(bool value);
  public:

  // @@protoc_insertion_point(class_scope:org.infinity.idm.Effector)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::TrackParam > params_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  double mix_;
  bool ison_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_effect_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Effector

// string name = 1;
inline void Effector::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& Effector::name() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Effector.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Effector::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:org.infinity.idm.Effector.name)
}
inline std::string* Effector::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:org.infinity.idm.Effector.name)
  return _s;
}
inline const std::string& Effector::_internal_name() const {
  return name_.Get();
}
inline void Effector::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Effector::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Effector::release_name() {
  // @@protoc_insertion_point(field_release:org.infinity.idm.Effector.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Effector::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:org.infinity.idm.Effector.name)
}

// bool isOn = 2;
inline void Effector::clear_ison() {
  ison_ = false;
}
inline bool Effector::_internal_ison() const {
  return ison_;
}
inline bool Effector::ison() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Effector.isOn)
  return _internal_ison();
}
inline void Effector::_internal_set_ison(bool value) {
  
  ison_ = value;
}
inline void Effector::set_ison(bool value) {
  _internal_set_ison(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Effector.isOn)
}

// double mix = 3;
inline void Effector::clear_mix() {
  mix_ = 0;
}
inline double Effector::_internal_mix() const {
  return mix_;
}
inline double Effector::mix() const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Effector.mix)
  return _internal_mix();
}
inline void Effector::_internal_set_mix(double value) {
  
  mix_ = value;
}
inline void Effector::set_mix(double value) {
  _internal_set_mix(value);
  // @@protoc_insertion_point(field_set:org.infinity.idm.Effector.mix)
}

// repeated .org.infinity.idm.TrackParam params = 4;
inline int Effector::_internal_params_size() const {
  return params_.size();
}
inline int Effector::params_size() const {
  return _internal_params_size();
}
inline ::org::infinity::idm::TrackParam* Effector::mutable_params(int index) {
  // @@protoc_insertion_point(field_mutable:org.infinity.idm.Effector.params)
  return params_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::TrackParam >*
Effector::mutable_params() {
  // @@protoc_insertion_point(field_mutable_list:org.infinity.idm.Effector.params)
  return &params_;
}
inline const ::org::infinity::idm::TrackParam& Effector::_internal_params(int index) const {
  return params_.Get(index);
}
inline const ::org::infinity::idm::TrackParam& Effector::params(int index) const {
  // @@protoc_insertion_point(field_get:org.infinity.idm.Effector.params)
  return _internal_params(index);
}
inline ::org::infinity::idm::TrackParam* Effector::_internal_add_params() {
  return params_.Add();
}
inline ::org::infinity::idm::TrackParam* Effector::add_params() {
  ::org::infinity::idm::TrackParam* _add = _internal_add_params();
  // @@protoc_insertion_point(field_add:org.infinity.idm.Effector.params)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::org::infinity::idm::TrackParam >&
Effector::params() const {
  // @@protoc_insertion_point(field_list:org.infinity.idm.Effector.params)
  return params_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace idm
}  // namespace infinity
}  // namespace org

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_effect_2eproto
