// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wave.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_wave_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_wave_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_wave_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_wave_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_wave_2eproto;
namespace infinity {
class Wave;
struct WaveDefaultTypeInternal;
extern WaveDefaultTypeInternal _Wave_default_instance_;
}  // namespace infinity
PROTOBUF_NAMESPACE_OPEN
template<> ::infinity::Wave* Arena::CreateMaybeMessage<::infinity::Wave>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace infinity {

// ===================================================================

class Wave final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:infinity.Wave) */ {
 public:
  inline Wave() : Wave(nullptr) {}
  ~Wave() override;
  explicit constexpr Wave(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Wave(const Wave& from);
  Wave(Wave&& from) noexcept
    : Wave() {
    *this = ::std::move(from);
  }

  inline Wave& operator=(const Wave& from) {
    CopyFrom(from);
    return *this;
  }
  inline Wave& operator=(Wave&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Wave& default_instance() {
    return *internal_default_instance();
  }
  static inline const Wave* internal_default_instance() {
    return reinterpret_cast<const Wave*>(
               &_Wave_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Wave& a, Wave& b) {
    a.Swap(&b);
  }
  inline void Swap(Wave* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Wave* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Wave* New() const final {
    return new Wave();
  }

  Wave* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Wave>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Wave& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Wave& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Wave* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "infinity.Wave";
  }
  protected:
  explicit Wave(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileFieldNumber = 4,
    kStartBeatFieldNumber = 1,
    kStartTickFieldNumber = 2,
    kLengthFieldNumber = 3,
    kDeviationFieldNumber = 5,
  };
  // string file = 4;
  void clear_file();
  const std::string& file() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file();
  PROTOBUF_MUST_USE_RESULT std::string* release_file();
  void set_allocated_file(std::string* file);
  private:
  const std::string& _internal_file() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file(const std::string& value);
  std::string* _internal_mutable_file();
  public:

  // uint32 startBeat = 1;
  void clear_startbeat();
  ::PROTOBUF_NAMESPACE_ID::uint32 startbeat() const;
  void set_startbeat(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_startbeat() const;
  void _internal_set_startbeat(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 startTick = 2;
  void clear_starttick();
  ::PROTOBUF_NAMESPACE_ID::uint32 starttick() const;
  void set_starttick(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_starttick() const;
  void _internal_set_starttick(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint64 length = 3;
  void clear_length();
  ::PROTOBUF_NAMESPACE_ID::uint64 length() const;
  void set_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_length() const;
  void _internal_set_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 deviation = 5;
  void clear_deviation();
  ::PROTOBUF_NAMESPACE_ID::uint64 deviation() const;
  void set_deviation(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_deviation() const;
  void _internal_set_deviation(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:infinity.Wave)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_;
  ::PROTOBUF_NAMESPACE_ID::uint32 startbeat_;
  ::PROTOBUF_NAMESPACE_ID::uint32 starttick_;
  ::PROTOBUF_NAMESPACE_ID::uint64 length_;
  ::PROTOBUF_NAMESPACE_ID::uint64 deviation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_wave_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Wave

// uint32 startBeat = 1;
inline void Wave::clear_startbeat() {
  startbeat_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Wave::_internal_startbeat() const {
  return startbeat_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Wave::startbeat() const {
  // @@protoc_insertion_point(field_get:infinity.Wave.startBeat)
  return _internal_startbeat();
}
inline void Wave::_internal_set_startbeat(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  startbeat_ = value;
}
inline void Wave::set_startbeat(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_startbeat(value);
  // @@protoc_insertion_point(field_set:infinity.Wave.startBeat)
}

// uint32 startTick = 2;
inline void Wave::clear_starttick() {
  starttick_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Wave::_internal_starttick() const {
  return starttick_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Wave::starttick() const {
  // @@protoc_insertion_point(field_get:infinity.Wave.startTick)
  return _internal_starttick();
}
inline void Wave::_internal_set_starttick(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  starttick_ = value;
}
inline void Wave::set_starttick(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_starttick(value);
  // @@protoc_insertion_point(field_set:infinity.Wave.startTick)
}

// uint64 length = 3;
inline void Wave::clear_length() {
  length_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Wave::_internal_length() const {
  return length_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Wave::length() const {
  // @@protoc_insertion_point(field_get:infinity.Wave.length)
  return _internal_length();
}
inline void Wave::_internal_set_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  length_ = value;
}
inline void Wave::set_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:infinity.Wave.length)
}

// string file = 4;
inline void Wave::clear_file() {
  file_.ClearToEmpty();
}
inline const std::string& Wave::file() const {
  // @@protoc_insertion_point(field_get:infinity.Wave.file)
  return _internal_file();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Wave::set_file(ArgT0&& arg0, ArgT... args) {
 
 file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:infinity.Wave.file)
}
inline std::string* Wave::mutable_file() {
  std::string* _s = _internal_mutable_file();
  // @@protoc_insertion_point(field_mutable:infinity.Wave.file)
  return _s;
}
inline const std::string& Wave::_internal_file() const {
  return file_.Get();
}
inline void Wave::_internal_set_file(const std::string& value) {
  
  file_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Wave::_internal_mutable_file() {
  
  return file_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Wave::release_file() {
  // @@protoc_insertion_point(field_release:infinity.Wave.file)
  return file_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Wave::set_allocated_file(std::string* file) {
  if (file != nullptr) {
    
  } else {
    
  }
  file_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), file,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:infinity.Wave.file)
}

// uint64 deviation = 5;
inline void Wave::clear_deviation() {
  deviation_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Wave::_internal_deviation() const {
  return deviation_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Wave::deviation() const {
  // @@protoc_insertion_point(field_get:infinity.Wave.deviation)
  return _internal_deviation();
}
inline void Wave::_internal_set_deviation(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  deviation_ = value;
}
inline void Wave::set_deviation(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_deviation(value);
  // @@protoc_insertion_point(field_set:infinity.Wave.deviation)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace infinity

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_wave_2eproto
